//$file${app::canopen::.::AO_canopen.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: g431b-esc.qm
// File:  ${app::canopen::.::AO_canopen.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${app::canopen::.::AO_canopen.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef AO_CANOPEN_H
#define AO_CANOPEN_H

#define CANOPEN_DEVICE_NODE_ID        (10)
#define CANOPEN_DEVICE_BITRATE_KBPS   (1000)

//$declare${app::canopen::AO_canopen} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${app::canopen::AO_canopen} ................................................
extern QActive * const AO_canopen;
//$enddecl${app::canopen::AO_canopen} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${app::canopen::CANOPEN_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${app::canopen::CANOPEN_ctor} ..............................................
void CANOPEN_ctor(
    FDCAN_HandleTypeDef * fdcan_handle,
    IRQn_Type irq);
//$enddecl${app::canopen::CANOPEN_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
